workflows:
  web-release:
    name: Build for Web
    max_build_duration: 60
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - flutter packages pub get
      - flutter config --enable-macos-desktop
      - find . -name "Podfile" -execdir pod install \;
      - flutter build macos
    artifacts:
      - build/macos/**/*.app.zip
      - build/macos/**/*.pkg
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - zhangguo@quanttide.com